# Generated by Django 6.0.1 on 2026-02-01 23:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_name', models.CharField(db_index=True, max_length=150)),
                ('founded_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('PROVIDER', 'Prestataire')], db_index=True, max_length=10)),
                ('provider_kind', models.CharField(blank=True, choices=[('FREELANCE', 'Freelance'), ('AGENCY', 'Agence')], db_index=True, help_text='Uniquement si role=PROVIDER', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('RCCM', 'RCCM'), ('STATUTES', 'Statuts'), ('OTHER', 'Autre')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to=users.models.upload_to_user_dir)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.agencydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('RCCM', 'RCCM'), ('LEGAL', 'Document juridique'), ('OTHER', 'Autre')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to=users.models.upload_to_user_dir)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.clientcompanydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_user_dir)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('COMPANY', 'Entreprise')], db_index=True, max_length=12)),
                ('city_or_region', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(db_index=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientIndividualDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('client_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_details', to='users.clientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientcompanydetails',
            name='client_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='users.clientprofile'),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_user_dir)),
                ('bio', models.TextField(validators=[users.models.validate_no_external_contact])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city_or_region', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(db_index=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('CV', 'CV'), ('CERTIFICATION', 'Certification'), ('PORTFOLIO', 'Portfolio'), ('IDENTITY', "Pièce d'identité"), ('OTHER', 'Autre'), ('RCCM', 'RCCM'), ('STATUTES', 'Statuts'), ('TAX', 'Document fiscal')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to=users.models.upload_to_user_dir)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('business_name', models.CharField(blank=True, help_text='Optionnel', max_length=120)),
                ('provider_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_details', to='users.providerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='agencydetails',
            name='provider_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_details', to='users.providerprofile'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='users_skill_is_acti_0e2697_idx')],
            },
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='providers', to='users.skill'),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(related_name='specialities', to='users.skill')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='users.speciality'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'provider_kind'], name='users_user_role_986cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider_kind__isnull', False), ('role', 'PROVIDER')), models.Q(models.Q(('role', 'PROVIDER'), _negated=True), ('provider_kind__isnull', True)), _connector='OR'), name='user_provider_kind_consistency'),
        ),
        migrations.AddIndex(
            model_name='agencydocument',
            index=models.Index(fields=['doc_type'], name='users_agenc_doc_typ_9d17a6_idx'),
        ),
        migrations.AddIndex(
            model_name='agencydocument',
            index=models.Index(fields=['agency', 'doc_type'], name='users_agenc_agency__d0fdec_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcompanydocument',
            index=models.Index(fields=['doc_type'], name='users_clien_doc_typ_d9303c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcompanydocument',
            index=models.Index(fields=['company', 'doc_type'], name='users_clien_company_2f75c9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['client_type'], name='users_clien_client__254b09_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['country', 'city_or_region'], name='users_clien_country_422217_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancedocument',
            index=models.Index(fields=['doc_type'], name='users_freel_doc_typ_774dda_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancedocument',
            index=models.Index(fields=['provider_profile', 'doc_type'], name='users_freel_provide_002ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancedocument',
            index=models.Index(fields=['provider_profile', 'created_at'], name='users_freel_provide_afd2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancedetails',
            index=models.Index(fields=['last_name', 'first_name'], name='users_freel_last_na_f9f898_idx'),
        ),
        migrations.AddIndex(
            model_name='agencydetails',
            index=models.Index(fields=['agency_name'], name='users_agenc_agency__9d12cb_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['is_active', 'name'], name='users_speci_is_acti_ea8e76_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['country', 'city_or_region'], name='users_provi_country_8788e5_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['hourly_rate'], name='users_provi_hourly__1ef39b_idx'),
        ),
    ]
